name: SDLC Local
values:
- key: base_url
  value: http://127.0.0.1:8001
- key: user_username
  value: postman_member
- key: user_email
  value: postman_member@example.com
- key: user_password
  value: ''
- key: admin_username
  value: admin
- key: admin_email
  value: admin@example.com
- key: admin_password
  value: ''
- key: new_admin_password
  value: ''
- key: user_access
  value: ''
- key: user_refresh
  value: ''
- key: admin_access
  value: ''
- key: admin_refresh
  value: ''
- key: reset_uid
  value: ''
- key: reset_token
  value: ''
- key: user_reset_uid
  value: ''
- key: user_reset_token
  value: ''
- key: new_user_password
  value: ''
